"""Unit and regression tests for continuous infinite WAV streaming handoff (RADIO-006C).

Validates:
1. Mathematical precision and architectural proof of the 22,826.051338-second invariant:
   - Liquidsoap 2.2.4 hardcoded data_len = 0xEFFFFFDB (4,026,531,803 bytes) from wav_aiff.ml.
   - Liquidsoap 2.2.4 hardcoded RIFF length = 0xEFFFFFFF (4,026,531,839 bytes = data_len + 36).
   - Stereo signed 16-bit PCM (4 bytes/sample) -> 1,006,632,950 total audio samples.
   - AAC 1024-sample frames -> 983,039 complete frames + 1,014 samples remainder.
   - AAC encoder internal pipeline buffer (libavcodec/aacenc.c:1234, s->planar_samples = 3 * 1024 = 3072 samples):
     initial_padding (1024 samples) + psychoacoustic MDCT window lookahead.
   - When WAV demuxer hits 0xEFFFFFDB, libavformat/wavdec.c:770 enters find_tag() on the live HTTP socket.
     Because the live socket never closes, av_read_frame() never returns EOF.
   - Without EOF, AAC encoder flush (frame = NULL) is never called; the 3 buffered frames remain unflushed.
   - Last muxed packet emitted is frame index 983,036:
     983,036 * 1024 = 1,006,628,864 samples = 4,026,515,456 bytes (0xEFFFC000).
   - FFTools progress calculation (fftools/ffmpeg_mux.c:357):
     av_rescale_q(1006628864, {1, 44100}, {1, 1000000}) = 22826051338 microseconds.
   - Exact match to historical production watchdog stall: out_time_us = 22826051338.
2. P2 Test Harness: Verified constructed stream.sh FFmpeg argv order via argument-recording stub.
3. Accelerated offline reproduction with real FFmpeg and machine-readable progress assertion:
   - Captures out_time_us boundary stall without -ignore_length 1.
   - Verifies continuous streaming past boundary to completion with -ignore_length 1.
"""
from __future__ import annotations

import http.server
import os
import shutil
import socketserver
import struct
import subprocess
import sys
import tempfile
import threading
import time
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# -----------------------------------------------------------------------------
# Canonical Liquidsoap 2.2.4 Header Fixture
# Verified byte-for-byte from savonet/liquidsoap v2.2.4 source tree:
# - src/core/tools/wav_aiff.ml (lines 227-234):
#     let header_len, data_len =
#       match len with
#         | None -> ("\255\255\255\239", "\219\255\255\239")
#         | Some v -> (int_string (v + 36), int_string v)
# - src/core/encoder/encoders/wav_encoder.ml (lines 32-52)
# - src/core/outputs/harbor_output.ml (lines 450-465)
# -----------------------------------------------------------------------------
LIQUIDSOAP_2_2_4_WAV_HEADER = (
    b"RIFF\xff\xff\xff\xef"          # 0x00: RIFF chunk length = 0xEFFFFFFF (4,026,531,839 bytes)
    b"WAVEfmt \x10\x00\x00\x00"      # 0x08: "WAVE", "fmt ", subchunk 1 size = 16 bytes
    b"\x01\x00\x02\x00"              # 0x14: format = 1 (PCM), channels = 2 (stereo)
    b"\x44\xac\x00\x00"              # 0x18: sample rate = 44,100 Hz
    b"\x10\xb1\x02\x00"              # 0x1C: byte rate = 176,400 bytes/sec (44100 * 2 * 16 / 8)
    b"\x04\x00\x10\x00"              # 0x20: block align = 4 bytes, bits per sample = 16
    b"data\xdb\xff\xff\xef"          # 0x24: "data", subchunk 2 size = 0xEFFFFFDB (4,026,531,803 bytes)
)


class TestRadioWavStreamingInvariants(unittest.TestCase):
    """Mathematical and architectural invariant tests for Liquidsoap/FFmpeg WAV streaming."""

    def test_liquidsoap_2_2_4_canonical_header_fixture_decoding(self) -> None:
        """Independently verifies that the canonical Liquidsoap 2.2.4 header decodes to 0xEFFFFFDB."""
        self.assertEqual(len(LIQUIDSOAP_2_2_4_WAV_HEADER), 44)
        self.assertTrue(LIQUIDSOAP_2_2_4_WAV_HEADER.startswith(b"RIFF"))
        self.assertIn(b"WAVEfmt ", LIQUIDSOAP_2_2_4_WAV_HEADER)
        self.assertIn(b"data", LIQUIDSOAP_2_2_4_WAV_HEADER)

        # Unpack fields according to standard RIFF/WAVE specification
        riff_magic, riff_size, wave_magic, fmt_magic, fmt_size, audio_fmt, num_channels, sample_rate, byte_rate, block_align, bits_per_sample, data_magic, data_size = struct.unpack(
            "<4sI4s4sIHHIIHH4sI",
            LIQUIDSOAP_2_2_4_WAV_HEADER,
        )

        self.assertEqual(riff_magic, b"RIFF")
        self.assertEqual(wave_magic, b"WAVE")
        self.assertEqual(fmt_magic, b"fmt ")
        self.assertEqual(fmt_size, 16)
        self.assertEqual(audio_fmt, 1)  # PCM
        self.assertEqual(num_channels, 2)  # Stereo
        self.assertEqual(sample_rate, 44100)
        self.assertEqual(byte_rate, 176400)
        self.assertEqual(block_align, 4)
        self.assertEqual(bits_per_sample, 16)
        self.assertEqual(data_magic, b"data")

        # Verify sentinel sizes generated by Liquidsoap for streaming WAV:
        # RIFF size = 0xEFFFFFFF = 4,026,531,839
        self.assertEqual(riff_size, 0xEFFFFFFF)
        self.assertEqual(riff_size, 4026531839)

        # data size = 0xEFFFFFDB = 4,026,531,803
        self.assertEqual(data_size, 0xEFFFFFDB)
        self.assertEqual(data_size, 4026531803)

        # RIFF size is strictly data size + 36 bytes (WAVE + fmt chunk + data header)
        self.assertEqual(riff_size - data_size, 36)

    def test_mathematical_precision_of_production_stall_invariant(self) -> None:
        """Proves that out_time_us = 22826051338 is an exact microsecond match to Liquidsoap's 0xEFFFFFDB boundary."""
        # 1. Liquidsoap header length formula from wav_aiff.ml:
        # header_len = "\255\255\255\239" -> 0xEFFFFFFF (4,026,531,839 bytes = 0xF0000000 - 1)
        # data_len   = "\219\255\255\239" -> 0xEFFFFFDB (4,026,531,803 bytes = 0xEFFFFFFF - 36)
        liquidsoap_data_bytes = 0xEFFFFFDB
        self.assertEqual(liquidsoap_data_bytes, 4026531803)

        # 2. Audio specifications: 44.1 kHz, stereo, 16-bit signed PCM
        sample_rate = 44100
        channels = 2
        bytes_per_sample_depth = 2
        bytes_per_sample_frame = channels * bytes_per_sample_depth  # 4 bytes
        self.assertEqual(bytes_per_sample_frame, 4)

        # Total audio samples in declared data chunk
        total_audio_samples = liquidsoap_data_bytes // bytes_per_sample_frame
        self.assertEqual(total_audio_samples, 1006632950)

        # 3. AAC encoder framing: 1024 samples per frame
        aac_frame_size = 1024
        total_available_aac_frames = total_audio_samples // aac_frame_size
        self.assertEqual(total_available_aac_frames, 983039)
        remainder_samples = total_audio_samples % aac_frame_size
        self.assertEqual(remainder_samples, 1014)

        # In FFmpeg, when demuxer reaches data_end, it enters find_tag() and blocks on the live HTTP socket.
        # Because av_read_frame() never returns EOF, the AAC encoder lookahead/FIFO buffer
        # (libavcodec/aacenc.c:1234, s->planar_samples capacity = 3 * 1024 = 3072 samples)
        # is never flushed. The last muxed packet emitted before the stall is frame 983,036:
        last_muxed_frames = 983036
        unflushed_buffered_frames = total_available_aac_frames - last_muxed_frames
        self.assertEqual(unflushed_buffered_frames, 3)

        # Samples in the 983,036 muxed AAC frames:
        muxed_samples = last_muxed_frames * aac_frame_size
        self.assertEqual(muxed_samples, 1006628864)
        muxed_pcm_bytes = muxed_samples * bytes_per_sample_frame
        self.assertEqual(muxed_pcm_bytes, 0xEFFFC000)
        self.assertEqual(muxed_pcm_bytes, 4026515456)

        # 4. Exact timestamp in seconds and microseconds
        # FFmpeg fftools/ffmpeg_mux.c:357 computes:
        # ost->last_mux_dts = av_rescale_q(pkt->dts, pkt->time_base, AV_TIME_BASE_Q)
        # where pkt->dts = 1006628864, time_base = {1, 44100}, AV_TIME_BASE_Q = {1, 1000000}
        exact_seconds = muxed_samples / sample_rate
        exact_us = exact_seconds * 1_000_000
        rounded_us = int(round(exact_us))

        # Expected production stall invariant observed in watchdog
        expected_watchdog_out_time_us = 22826051338
        self.assertEqual(rounded_us, expected_watchdog_out_time_us)
        self.assertAlmostEqual(exact_seconds, 22826.051338, places=6)

    def test_stream_sh_places_ignore_length_before_audio_input_static(self) -> None:
        """Verifies stream.sh includes -ignore_length 1 as an input option preceding -i."""
        stream_sh = REPO_ROOT / "apps" / "radio" / "stream.sh"
        self.assertTrue(stream_sh.is_file(), f"stream.sh missing: {stream_sh}")
        text = stream_sh.read_text(encoding="utf-8")

        self.assertIn("-ignore_length 1", text)
        self.assertIn("STREAM_INPUT_AUDIO", text)

        ignore_idx = text.index("-ignore_length 1")
        audio_in_idx = text.index('-i "${STREAM_INPUT_AUDIO}"')
        self.assertLess(
            ignore_idx,
            audio_in_idx,
            "-ignore_length 1 must strictly precede audio input (-i) in stream.sh",
        )

    def test_stream_sh_constructed_ffmpeg_argv_command_order(self) -> None:
        """P2: Tests the actual constructed FFmpeg argv via argument-recording stub.

        Guarantees that -ignore_length 1:
        1. Is present in the constructed argv array.
        2. Is strictly followed by '1'.
        3. Strictly precedes the audio input option (-i).
        4. Applies strictly to the audio input and not preceding inputs.
        """
        bash = shutil.which("bash") or "C:/Program Files/Git/bin/bash.exe"
        if not Path(bash).is_file():
            self.skipTest("bash binary not available in environment")

        stream_sh = REPO_ROOT / "apps" / "radio" / "stream.sh"
        self.assertTrue(stream_sh.is_file(), f"stream.sh missing: {stream_sh}")

        with tempfile.TemporaryDirectory(prefix="radio_argv_order_") as tmpdir:
            tmp = Path(tmpdir)
            assets_dir = tmp / "assets"
            assets_dir.mkdir(parents=True)
            fake_loop = assets_dir / "visual_loop.mp4"
            fake_loop.write_text("fake video content", encoding="utf-8")

            bin_dir = tmp / "bin"
            bin_dir.mkdir(parents=True)
            mock_ffmpeg = bin_dir / "ffmpeg"
            args_log = tmp / "ffmpeg_argv.txt"
            mock_ffmpeg.write_text(
                "#!/usr/bin/env bash\n"
                f'printf "%s\\n" "$@" > "{args_log.as_posix()}"\n'
                "exit 0\n",
                encoding="utf-8",
            )
            os.chmod(str(mock_ffmpeg), 0o755)

            test_audio_url = "http://127.0.0.1:8000/radio.wav"
            env = os.environ.copy()
            env["PATH"] = str(bin_dir) + os.pathsep + env.get("PATH", "")
            env["BASE_DIR"] = str(tmp)
            env["STREAM_OUTPUT_MODE"] = "file"
            env["STREAM_OUTPUT_FILE"] = str(tmp / "out.flv")
            env["STREAM_INPUT_AUDIO"] = test_audio_url

            res = subprocess.run(
                [bash, stream_sh.as_posix()],
                env=env,
                capture_output=True,
                text=True,
                timeout=10,
            )
            self.assertEqual(res.returncode, 0, f"stream.sh failed: {res.stderr}")

            self.assertTrue(args_log.is_file(), "mock ffmpeg did not generate argv log")
            argv = args_log.read_text(encoding="utf-8").splitlines()

            # Verify presence and order in actual argv array
            self.assertIn("-ignore_length", argv)
            ignore_idx = argv.index("-ignore_length")
            self.assertEqual(argv[ignore_idx + 1], "1")

            # Verify that the input following -ignore_length 1 is the audio URL
            audio_i_idx = None
            for idx in range(ignore_idx + 1, len(argv)):
                if argv[idx] == "-i":
                    audio_i_idx = idx
                    break

            self.assertIsNotNone(audio_i_idx, "-i must follow -ignore_length 1")
            assert audio_i_idx is not None
            self.assertEqual(
                argv[audio_i_idx + 1],
                test_audio_url,
                f"Input following -ignore_length must be STREAM_INPUT_AUDIO ({test_audio_url})",
            )


class TestRadioWavDemuxerReproduction(unittest.TestCase):
    """Accelerated local reproduction of WAV demuxer stall and fix verification."""

    def setUp(self) -> None:
        self.ffmpeg = shutil.which("ffmpeg")
        if not self.ffmpeg:
            self.skipTest("ffmpeg binary not available in environment")

    def test_accelerated_wav_header_boundary_stall_and_fix(self) -> None:
        """Demonstrates that a synthetic WAV stream stalls without -ignore_length 1 and passes with it.

        Uses the exact Liquidsoap header structure and remainder formula:
        Declared length: 86 frames * 1024 * 4 + 1014 remainder * 4 + 3 odd bytes = 356,315 bytes (~2.02 seconds).
        Captures machine-readable progress (out_time_us) and asserts boundary stall behavior.
        """
        SCALED_FRAMES = 86
        REMAINDER_SAMPLES = 1014
        SCALED_DATA_LEN = SCALED_FRAMES * 1024 * 4 + REMAINDER_SAMPLES * 4 + 3

        # Form scaled RIFF/WAV header matching Liquidsoap 2.2.4 structure
        scaled_header = (
            b"RIFF" + struct.pack("<I", SCALED_DATA_LEN + 36) +
            b"WAVEfmt \x10\x00\x00\x00"
            b"\x01\x00\x02\x00"
            b"\x44\xac\x00\x00"
            b"\x10\xb1\x02\x00"
            b"\x04\x00\x10\x00"
            b"data" + struct.pack("<I", SCALED_DATA_LEN)
        )

        class MockHarborHandler(http.server.BaseHTTPRequestHandler):
            def do_GET(self) -> None:
                self.send_response(200)
                self.send_header("Content-type", "audio/wav")
                self.end_headers()

                try:
                    self.wfile.write(scaled_header)
                    # Stream audio data up to declared boundary and continue past it
                    chunk = b"\x00" * 4096
                    sent = 0
                    while sent < SCALED_DATA_LEN:
                        to_send = min(4096, SCALED_DATA_LEN - sent)
                        self.wfile.write(chunk[:to_send])
                        sent += to_send
                    # Continue streaming silence past declared length (infinite stream)
                    for _ in range(300):
                        self.wfile.write(chunk)
                        time.sleep(0.01)
                except (OSError, BrokenPipeError, ConnectionResetError, ConnectionAbortedError):
                    pass

            def log_message(self, format: str, *args: object) -> None:
                pass

        server = socketserver.TCPServer(("127.0.0.1", 0), MockHarborHandler)
        port = server.server_address[1]
        server_thread = threading.Thread(target=server.serve_forever, daemon=True)
        server_thread.start()

        stream_url = f"http://127.0.0.1:{port}/radio.wav"

        try:
            # Case 1: WITHOUT -ignore_length 1
            # FFmpeg requests 5 seconds of audio (-t 5), but header declares ~2.02 seconds.
            # Without -ignore_length 1, FFmpeg demuxer halts at declared boundary; out_time_us stops advancing.
            cmd_unfixed = [
                self.ffmpeg,
                "-y",
                "-i",
                stream_url,
                "-c:a",
                "aac",
                "-t",
                "5",
                "-progress",
                "pipe:1",
                "-f",
                "null",
                "-",
            ]
            proc_unfixed = subprocess.Popen(
                cmd_unfixed,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                text=True,
            )
            progress_unfixed: list[int] = []
            start = time.time()
            while time.time() - start < 3.5:
                assert proc_unfixed.stdout is not None
                line = proc_unfixed.stdout.readline()
                if not line:
                    break
                if line.startswith("out_time_us="):
                    try:
                        progress_unfixed.append(int(line.strip().split("=")[1]))
                    except ValueError:
                        pass

            proc_unfixed.kill()
            proc_unfixed.wait(timeout=2.0)
            if proc_unfixed.stdout is not None:
                proc_unfixed.stdout.close()

            # Assert that demuxer progress stalled near the 2.02-second boundary and did not reach 5 seconds
            self.assertTrue(len(progress_unfixed) > 0, "No progress lines captured from unfixed FFmpeg")
            last_unfixed_us = progress_unfixed[-1]
            self.assertLess(
                last_unfixed_us,
                3_000_000,
                f"Unfixed FFmpeg should have stalled at ~2.02s boundary; reached {last_unfixed_us} us",
            )

            # Case 2: WITH -ignore_length 1
            # Demuxer ignores declared length; successfully consumes full 5 seconds.
            cmd_fixed = [
                self.ffmpeg,
                "-y",
                "-ignore_length",
                "1",
                "-i",
                stream_url,
                "-c:a",
                "aac",
                "-t",
                "5",
                "-progress",
                "pipe:1",
                "-f",
                "null",
                "-",
            ]
            proc_fixed = subprocess.Popen(
                cmd_fixed,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                text=True,
            )
            progress_fixed: list[int] = []
            try:
                assert proc_fixed.stdout is not None
                for line in proc_fixed.stdout:
                    if line.startswith("out_time_us="):
                        try:
                            progress_fixed.append(int(line.strip().split("=")[1]))
                        except ValueError:
                            pass
                proc_fixed.wait(timeout=6.0)
            except subprocess.TimeoutExpired:
                proc_fixed.kill()
                self.fail("FFmpeg stalled even with -ignore_length 1")
            finally:
                if proc_fixed.stdout is not None:
                    proc_fixed.stdout.close()

            self.assertEqual(
                proc_fixed.returncode,
                0,
                f"Expected clean exit 0 with -ignore_length 1, got {proc_fixed.returncode}",
            )
            self.assertTrue(len(progress_fixed) > 0, "No progress lines captured from fixed FFmpeg")
            last_fixed_us = progress_fixed[-1]
            self.assertGreaterEqual(
                last_fixed_us,
                4_900_000,
                f"Fixed FFmpeg should have reached 5.0s (5,000,000 us); reached {last_fixed_us} us",
            )

        finally:
            server.shutdown()
            server.server_close()


if __name__ == "__main__":
    unittest.main()
